"""
Path model for FlowPath application.

A Path represents a complete set of step-by-step instructions.
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional, List


@dataclass
class Path:
    """
    Represents a step-by-step instruction path.

    Attributes:
        id: Unique identifier (auto-generated by database)
        title: The title of the path
        category: Category for organization (e.g., 'LMS', 'Admin')
        tags: Comma-separated tags for filtering
        description: Detailed description of what this path covers
        creator: Username or identifier of the path creator
        created_at: Timestamp when the path was created
        updated_at: Timestamp when the path was last modified
    """
    title: str
    category: str = ""
    tags: str = ""
    description: str = ""
    creator: str = ""
    id: Optional[int] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None

    def __post_init__(self):
        """Set timestamps if not provided."""
        now = datetime.now()
        if self.created_at is None:
            self.created_at = now
        if self.updated_at is None:
            self.updated_at = now

    @property
    def tag_list(self) -> List[str]:
        """Return tags as a list."""
        if not self.tags:
            return []
        return [tag.strip() for tag in self.tags.split(',') if tag.strip()]

    def add_tag(self, tag: str) -> None:
        """Add a tag to the path."""
        tags = self.tag_list
        if tag not in tags:
            tags.append(tag)
            self.tags = ', '.join(tags)

    def remove_tag(self, tag: str) -> None:
        """Remove a tag from the path."""
        tags = self.tag_list
        if tag in tags:
            tags.remove(tag)
            self.tags = ', '.join(tags)

    def to_dict(self) -> dict:
        """Convert to dictionary for serialization."""
        return {
            'id': self.id,
            'title': self.title,
            'category': self.category,
            'tags': self.tags,
            'description': self.description,
            'creator': self.creator,
            'created_at': self.created_at.isoformat() if self.created_at else None,
            'updated_at': self.updated_at.isoformat() if self.updated_at else None,
        }

    @classmethod
    def from_dict(cls, data: dict) -> 'Path':
        """Create a Path from a dictionary."""
        created_at = None
        updated_at = None

        if data.get('created_at'):
            if isinstance(data['created_at'], str):
                created_at = datetime.fromisoformat(data['created_at'])
            else:
                created_at = data['created_at']

        if data.get('updated_at'):
            if isinstance(data['updated_at'], str):
                updated_at = datetime.fromisoformat(data['updated_at'])
            else:
                updated_at = data['updated_at']

        return cls(
            id=data.get('id'),
            title=data.get('title', ''),
            category=data.get('category', ''),
            tags=data.get('tags', ''),
            description=data.get('description', ''),
            creator=data.get('creator', ''),
            created_at=created_at,
            updated_at=updated_at,
        )

    def __repr__(self) -> str:
        return f"Path(id={self.id}, title='{self.title}', category='{self.category}')"
