"""
Step model for FlowPath application.

A Step represents a single step within a Path.
"""

from dataclasses import dataclass
from datetime import datetime
from typing import Optional
import os


@dataclass
class Step:
    """
    Represents a single step in an instruction path.

    Attributes:
        id: Unique identifier (auto-generated by database)
        path_id: Foreign key to the parent Path
        step_number: Order of this step within the path (1-indexed)
        instructions: Text instructions for this step
        screenshot_path: File path to the screenshot image (if any)
        created_at: Timestamp when the step was created
        updated_at: Timestamp when the step was last modified
    """
    path_id: int
    step_number: int
    instructions: str = ""
    screenshot_path: Optional[str] = None
    id: Optional[int] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None

    def __post_init__(self):
        """Set timestamps if not provided."""
        now = datetime.now()
        if self.created_at is None:
            self.created_at = now
        if self.updated_at is None:
            self.updated_at = now

    @property
    def has_screenshot(self) -> bool:
        """Check if this step has a screenshot."""
        return bool(self.screenshot_path and os.path.exists(self.screenshot_path))

    def to_dict(self) -> dict:
        """Convert to dictionary for serialization."""
        return {
            'id': self.id,
            'path_id': self.path_id,
            'step_number': self.step_number,
            'instructions': self.instructions,
            'screenshot_path': self.screenshot_path,
            'created_at': self.created_at.isoformat() if self.created_at else None,
            'updated_at': self.updated_at.isoformat() if self.updated_at else None,
        }

    @classmethod
    def from_dict(cls, data: dict) -> 'Step':
        """Create a Step from a dictionary."""
        created_at = None
        updated_at = None

        if data.get('created_at'):
            if isinstance(data['created_at'], str):
                created_at = datetime.fromisoformat(data['created_at'])
            else:
                created_at = data['created_at']

        if data.get('updated_at'):
            if isinstance(data['updated_at'], str):
                updated_at = datetime.fromisoformat(data['updated_at'])
            else:
                updated_at = data['updated_at']

        return cls(
            id=data.get('id'),
            path_id=data.get('path_id'),
            step_number=data.get('step_number', 1),
            instructions=data.get('instructions', ''),
            screenshot_path=data.get('screenshot_path'),
            created_at=created_at,
            updated_at=updated_at,
        )

    def __repr__(self) -> str:
        return f"Step(id={self.id}, path_id={self.path_id}, step_number={self.step_number})"
